version: '3.9'

services:
  storage_web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/storage
    ports:
      - 8000:8000
    networks:
      - l

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: keycloak
    ports:
      - 8080:8080
    networks:
      - l

networks:
  l: