version: '3.7'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: storage_user
      POSTGRES_USER: storage_user
      POSTGRES_DB: storage_db
      POSTGRESS_INITDB_ARGS: "-A md5"
    ports:
      - "54321:5432"

  web:
    build: .
    command: gunicorn storage.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./static:/static
    expose:
      - 8000
    depends_on:
      - db

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PROXY_ADDRESS_FORWADING: "true"
      REDIRECT_SOCKET: "proxy-https"
      KC_HOSTNAME: 'keycloak.net'
    expose:
      - 8080

  nginx:
    build: ./nginx
    volumes:
      - ./static:/static
    depends_on:
      - web
      - keycloak
    ports:
      - 80:80
